import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";

import Heading from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex TS",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`min-h-screen p-0 ${inter.className}`}>
        <Providers>
          <main className={`p-0 ${inter.className}`}>
            <Heading />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
